package ui.screens.ideas

import androidx.compose.foundation.background
import androidx.compose.foundation.border
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.size
import androidx.compose.foundation.layout.statusBarsPadding
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.itemsIndexed
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material3.Text
import androidx.compose.material3.TextField
import androidx.compose.material3.TextFieldDefaults
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import ui.components.PrimaryButton
import ui.navigation.AppNavigationActions
import ui.theme.Background
import ui.theme.BorderSecondary
import ui.theme.OnBackground
import ui.theme.Primary
import ui.theme.PrimaryContainer
import ui.theme.Surface
import ui.theme.TextSecondary
import ui.theme.TextTertiary

private val demoIdeas = listOf(
    "5 ошибок при варке пасты — исправляем вместе",
    "Что итальянцы думают о нашей карбонаре",
    "Секрет идеального соуса — 3 ингредиента",
    "Паста за 10 минут когда нет времени",
    "Топ-3 пасты которые надо попробовать",
    "Как правильно варить пасту аль денте",
    "Ошибка которую делают все новички на кухне",
    "Бюджетный ужин за 200 рублей — показываю",
    "Итальянская кухня дома: 5 простых рецептов",
    "Почему я перестал покупать соус в магазине",
)

@Composable
fun IdeasScreen(navigationActions: AppNavigationActions) {
    var niche by remember { mutableStateOf("Кулинарный блог") }
    var isGenerated by remember { mutableStateOf(true) }

    Column(
        modifier = Modifier
            .fillMaxSize()
            .background(Background)
            .statusBarsPadding(),
    ) {
        Column(modifier = Modifier.padding(horizontal = 20.dp)) {
            Spacer(Modifier.height(16.dp))
            Row(
                verticalAlignment = Alignment.CenterVertically,
                horizontalArrangement = Arrangement.SpaceBetween,
                modifier = Modifier.fillMaxWidth(),
            ) {
                Row(verticalAlignment = Alignment.CenterVertically, horizontalArrangement = Arrangement.spacedBy(10.dp)) {
                    Box(
                        modifier = Modifier.size(32.dp).clip(RoundedCornerShape(10.dp)).background(PrimaryContainer).clickable { navigationActions.navigateBack() },
                        contentAlignment = Alignment.Center,
                    ) { Text("←", fontSize = 16.sp, color = Primary) }
                    Text("Придумай темы", fontSize = 16.sp, fontWeight = FontWeight.Medium, color = OnBackground)
                }
                if (isGenerated) {
                    Box(
                        modifier = Modifier.clip(RoundedCornerShape(20.dp)).background(PrimaryContainer).padding(horizontal = 8.dp, vertical = 4.dp)
                    ) { Text("30 идей", fontSize = 9.sp, color = Primary, fontWeight = FontWeight.Medium) }
                }
            }
            Spacer(Modifier.height(14.dp))

            Text("Твоя ниша", fontSize = 12.sp, color = TextSecondary)
            Spacer(Modifier.height(4.dp))
            TextField(
                value = niche,
                onValueChange = { niche = it },
                modifier = Modifier.fillMaxWidth().clip(RoundedCornerShape(12.dp)).border(0.5.dp, BorderSecondary, RoundedCornerShape(12.dp)),
                placeholder = { Text("Например: кулинария, фитнес, красота...", fontSize = 12.sp, color = TextTertiary) },
                colors = TextFieldDefaults.colors(
                    focusedContainerColor = Surface,
                    unfocusedContainerColor = Surface,
                    focusedIndicatorColor = Color.Transparent,
                    unfocusedIndicatorColor = Color.Transparent,
                ),
                singleLine = true,
            )
            Spacer(Modifier.height(6.dp))
            Text("Кулинарный блог · Instagram", fontSize = 10.sp, color = TextTertiary)
            Spacer(Modifier.height(12.dp))
        }

        if (isGenerated) {
            LazyColumn(
                modifier = Modifier.weight(1f).padding(horizontal = 20.dp),
                verticalArrangement = Arrangement.spacedBy(0.dp),
            ) {
                itemsIndexed(demoIdeas) { idx, idea ->
                    IdeaItem(number = idx + 1, text = idea)
                }
                item {
                    Text(
                        "+ ещё 20 идей ↓",
                        fontSize = 11.sp,
                        color = Primary,
                        modifier = Modifier.fillMaxWidth().padding(vertical = 10.dp),
                        textAlign = androidx.compose.ui.text.style.TextAlign.Center,
                    )
                }
                item { Spacer(Modifier.height(16.dp)) }
            }
        } else {
            Spacer(Modifier.weight(1f))
        }

        Row(
            modifier = Modifier.padding(horizontal = 20.dp, vertical = 16.dp),
            horizontalArrangement = Arrangement.spacedBy(8.dp),
        ) {
            Box(
                modifier = Modifier
                    .weight(1f)
                    .clip(RoundedCornerShape(14.dp))
                    .background(Surface)
                    .border(0.5.dp, BorderSecondary, RoundedCornerShape(14.dp))
                    .clickable { isGenerated = true }
                    .padding(vertical = 13.dp),
                contentAlignment = Alignment.Center,
            ) { Text("Обновить", fontSize = 12.sp, color = TextSecondary) }

            Box(
                modifier = Modifier
                    .weight(1f)
                    .clip(RoundedCornerShape(14.dp))
                    .background(Primary)
                    .clickable { isGenerated = true }
                    .padding(vertical = 13.dp),
                contentAlignment = Alignment.Center,
            ) { Text("Сохранить все", fontSize = 12.sp, color = Color.White, fontWeight = FontWeight.Medium) }
        }
    }
}

@Composable
private fun IdeaItem(number: Int, text: String) {
    Row(
        modifier = Modifier
            .fillMaxWidth()
            .clickable { }
            .padding(vertical = 8.dp),
        verticalAlignment = Alignment.Top,
        horizontalArrangement = Arrangement.spacedBy(8.dp),
    ) {
        Text(
            "$number",
            fontSize = 11.sp,
            fontWeight = FontWeight.Medium,
            color = Primary,
            modifier = Modifier.padding(top = 1.dp),
        )
        Text(text, fontSize = 12.sp, color = OnBackground, lineHeight = 18.sp, modifier = Modifier.weight(1f))
    }
    Box(modifier = Modifier.fillMaxWidth().height(0.5.dp).background(BorderSecondary))
}
