package ui.screens.textpost

import androidx.compose.foundation.background
import androidx.compose.foundation.border
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.size
import androidx.compose.foundation.layout.statusBarsPadding
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.verticalScroll
import androidx.compose.material3.Text
import androidx.compose.material3.TextField
import androidx.compose.material3.TextFieldDefaults
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import ui.components.PrimaryButton
import ui.components.SectionTitle
import ui.navigation.AppNavigationActions
import ui.theme.Background
import ui.theme.BorderSecondary
import ui.theme.OnBackground
import ui.theme.Primary
import ui.theme.PrimaryContainer
import ui.theme.PrimaryContainerDark
import ui.theme.Secondary
import ui.theme.SecondaryContainer
import ui.theme.Surface
import ui.theme.TextSecondary
import ui.theme.TextTertiary

private val platforms = listOf("Instagram", "TikTok", "VK", "YouTube")
private val tones = listOf("Дружелюбный", "Экспертный", "С юмором")

@Composable
fun TextPostScreen(navigationActions: AppNavigationActions) {
    var topic by remember { mutableStateOf("") }
    var selectedPlatform by remember { mutableStateOf(0) }
    var selectedTone by remember { mutableStateOf(0) }
    var generatedText by remember { mutableStateOf("") }
    var isGenerated by remember { mutableStateOf(false) }

    // Demo result
    val demoResult = "Идеальная паста карбонара за 15 минут 🍝 Никаких секретов — только правильная техника!\n\n#рецепты #паста #карбонара #кулинария #итальянскаякухня"

    Column(
        modifier = Modifier
            .fillMaxSize()
            .background(Background)
            .statusBarsPadding(),
    ) {
        Column(
            modifier = Modifier
                .weight(1f)
                .verticalScroll(rememberScrollState())
                .padding(horizontal = 20.dp),
        ) {
            Spacer(Modifier.height(16.dp))

            Row(verticalAlignment = Alignment.CenterVertically, horizontalArrangement = Arrangement.spacedBy(10.dp)) {
                Box(
                    modifier = Modifier.size(32.dp).clip(RoundedCornerShape(10.dp)).background(PrimaryContainer).clickable { navigationActions.navigateBack() },
                    contentAlignment = Alignment.Center,
                ) { Text("←", fontSize = 16.sp, color = Primary) }
                Text("Текст для поста", fontSize = 16.sp, fontWeight = FontWeight.Medium, color = OnBackground)
            }
            Spacer(Modifier.height(18.dp))

            Text("О чём пост?", fontSize = 12.sp, color = TextSecondary)
            Spacer(Modifier.height(4.dp))
            TextField(
                value = topic,
                onValueChange = { topic = it },
                modifier = Modifier.fillMaxWidth().clip(RoundedCornerShape(12.dp)).border(0.5.dp, BorderSecondary, RoundedCornerShape(12.dp)),
                placeholder = { Text("Паста карбонара — рецепт за 15 минут", fontSize = 12.sp, color = TextTertiary) },
                colors = TextFieldDefaults.colors(
                    focusedContainerColor = Surface,
                    unfocusedContainerColor = Surface,
                    focusedIndicatorColor = Color.Transparent,
                    unfocusedIndicatorColor = Color.Transparent,
                ),
            )
            Spacer(Modifier.height(14.dp))

            SectionTitle("ПЛАТФОРМА")
            Spacer(Modifier.height(6.dp))
            Row(horizontalArrangement = Arrangement.spacedBy(5.dp)) {
                platforms.forEachIndexed { idx, p ->
                    val sel = selectedPlatform == idx
                    Box(
                        modifier = Modifier
                            .clip(RoundedCornerShape(20.dp))
                            .background(if (sel) PrimaryContainer else Color.Transparent)
                            .border(0.5.dp, if (sel) PrimaryContainerDark else BorderSecondary, RoundedCornerShape(20.dp))
                            .clickable { selectedPlatform = idx }
                            .padding(horizontal = 10.dp, vertical = 5.dp),
                    ) { Text(if (sel) "$p ✓" else p, fontSize = 10.sp, color = if (sel) Primary else TextSecondary) }
                }
            }
            Spacer(Modifier.height(14.dp))

            SectionTitle("ТОН")
            Spacer(Modifier.height(6.dp))
            Row(horizontalArrangement = Arrangement.spacedBy(5.dp)) {
                tones.forEachIndexed { idx, t ->
                    val sel = selectedTone == idx
                    Box(
                        modifier = Modifier
                            .clip(RoundedCornerShape(20.dp))
                            .background(if (sel) PrimaryContainer else Color.Transparent)
                            .border(0.5.dp, if (sel) PrimaryContainerDark else BorderSecondary, RoundedCornerShape(20.dp))
                            .clickable { selectedTone = idx }
                            .padding(horizontal = 10.dp, vertical = 5.dp),
                    ) { Text(if (sel) "$t ✓" else t, fontSize = 10.sp, color = if (sel) Primary else TextSecondary) }
                }
            }

            if (isGenerated) {
                Spacer(Modifier.height(16.dp))
                Box(modifier = Modifier.fillMaxWidth().height(0.5.dp).background(BorderSecondary))
                Spacer(Modifier.height(12.dp))
                Text("Результат", fontSize = 13.sp, fontWeight = FontWeight.Medium, color = OnBackground)
                Spacer(Modifier.height(6.dp))
                Box(
                    modifier = Modifier.fillMaxWidth().clip(RoundedCornerShape(12.dp)).background(PrimaryContainer).border(0.5.dp, PrimaryContainerDark, RoundedCornerShape(12.dp)).padding(12.dp),
                ) {
                    Text(demoResult, fontSize = 12.sp, color = Primary.copy(0.9f), lineHeight = 18.sp)
                }
                Spacer(Modifier.height(8.dp))
                Row(horizontalArrangement = Arrangement.spacedBy(6.dp)) {
                    listOf("Изменить", "Другой", "Копировать").forEachIndexed { idx, label ->
                        Box(
                            modifier = Modifier
                                .weight(1f)
                                .clip(RoundedCornerShape(10.dp))
                                .background(if (idx == 2) Primary else Surface)
                                .border(0.5.dp, if (idx == 2) Color.Transparent else BorderSecondary, RoundedCornerShape(10.dp))
                                .clickable { }
                                .padding(vertical = 8.dp),
                            contentAlignment = Alignment.Center,
                        ) { Text(label, fontSize = 10.sp, color = if (idx == 2) Color.White else TextSecondary) }
                    }
                }
            }
            Spacer(Modifier.height(20.dp))
        }

        Box(modifier = Modifier.padding(horizontal = 20.dp, vertical = 16.dp)) {
            PrimaryButton(
                text = if (isGenerated) "Сгенерировать заново" else "Написать текст",
                onClick = { isGenerated = true },
            )
        }
    }
}
